import { CartSummaryItemData } from "types";
import { ProductDetails } from "types";

export const ProductsWithProfile: CartSummaryItemData[] = [
  {
    shop: {
      id: "1",
      imageUrl: "/shop-2.jpeg",
      name: "Wiaah",
    },
    item: {
      id: "1",
      imageUrl:
        "https://cdn.mena-tech.com/wp-content/uploads/2021/08/MR-Future-Products-2020-2.png",
      name: "item1",
      price: 15,
      qty: 3,
      shippingMotheds: [
        {
          deliveryTime: {
            from: 5,
            to: 7,
          },
          name: "European union",
          value: "european_union",
        },
        {
          deliveryTime: {
            from: 1,
            to: 3,
          },
          name: "Click & Collect",
          value: "click_and_collect",
        },
        {
          deliveryTime: {
            from: 6,
            to: 8,
          },
          name: "International",
          value: "international",
        },
      ],

      colors: [],
      sizes: ["One Size"],
      type: "product",
      cashback: {
        unit: "%",
        value: 10,
      },
      discount: {
        unit: "$",
        value: 5,
      },
      oldPrice: 20,
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto doloremque molestiae perferendis saepe? Tenetur, eligendi. Excepturi voluptate harum fuga! Consequatur?`,
    },
  },
  {
    shop: {
      id: "45",
      imageUrl: "/shop-2.jpeg",
      name: "Wiaah",
    },
    item: {
      id: "1",
      imageUrl:
        "https://www.eisenberg.com/upload/images/eisenberg/4f/173_BANNER-CATEGORIE-FRAGRANCE-1170X500PX.jpeg",
      name: "item1",
      price: 15,
      qty: 3,
      shippingMotheds: [
        {
          deliveryTime: {
            from: 5,
            to: 7,
          },
          name: "European union",
          value: "european_union",
        },
        {
          deliveryTime: {
            from: 1,
            to: 3,
          },
          name: "Click & Collect",
          value: "click_and_collect",
        },
        {
          deliveryTime: {
            from: 6,
            to: 8,
          },
          name: "International",
          value: "international",
        },
      ],

      colors: ["relay blue/yellow"],
      sizes: ["One Size"],
      type: "product",
      cashback: {
        unit: "%",
        value: 10,
      },
      discount: {
        unit: "$",
        value: 5,
      },
      oldPrice: 20,
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto doloremque molestiae perferendis saepe? Tenetur, eligendi. Excepturi voluptate harum fuga! Consequatur?`,
    },
  },
  {
    shop: {
      id: "2",
      imageUrl: "/shop.jpeg",
      name: "Wiaah",
    },
    item: {
      id: "2",
      imageUrl:
        "https://static.barcelo.com/content/dam/bhg/master/es/hoteles/guatemala/guatemala-city/barcelo-guatemala-city/carrusel/BGUA_VIEW_01.jpg.bhgimg.optm1100.jpg/1604614790315.jpg",
      name: "item1",
      price: 15,
      qty: 3,
      shippingMotheds: [
        {
          deliveryTime: {
            from: 5,
            to: 7,
          },
          name: "European union",
          value: "european_union",
        },
        {
          deliveryTime: {
            from: 1,
            to: 3,
          },
          name: "Click & Collect",
          value: "click_and_collect",
        },
        {
          deliveryTime: {
            from: 6,
            to: 8,
          },
          name: "International",
          value: "international",
        },
      ],
      type: "service",
      location: "123 main st apt 4 atlana ga",
      date: Date.now(),
      eventDuration: 20,
      eventAdresses: "test@adress.com",
      cashback: {
        unit: "%",
        value: 10,
      },
      discount: {
        unit: "$",
        value: 5,
      },
      oldPrice: 20,
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto doloremque molestiae perferendis saepe? Tenetur, eligendi. Excepturi voluptate harum fuga! Consequatur?`,
    },
  },
];

export const products: ProductDetails[] = [
  {
    id: "1",
    price: 15,
    imgUrl:
      "https://cdn.mena-tech.com/wp-content/uploads/2021/08/MR-Future-Products-2020-2.png",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "2",

    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://images.prismic.io/rushordertees-web/c46d32cd-469a-49a9-b175-7362171d29a7_Custom+Short+Sleeve+T-Shirt.jpg?auto=compress%2Cformat&rect=0%2C0%2C800%2C900&w=800&h=900",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    off: 10,
    type: "service",
    oldPrice: 600,
  },
  {
    id: "3",
    price: 15,
    imgUrl:
      "https://4.imimg.com/data4/AA/HC/MY-26596027/men-s-fancy-t-shirt-500x500.jpg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "service",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "4",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://contents.mediadecathlon.com/p1981373/k$9b63009207eb708712157b83d42dd74b/adults-category-3-hiking-sunglasses-mh140.jpg?&f=800x800",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "5",
    price: 15,
    imgUrl:
      "https://www.eisenberg.com/upload/images/eisenberg/4f/173_BANNER-CATEGORIE-FRAGRANCE-1170X500PX.jpeg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "product",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "6",
    name: "test item",
    imgUrl:
      "https://cdn.shopify.com/s/files/1/0505/7019/9217/products/P04.jpg?v=1613769249",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "7",
    price: 15,
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-secret-sneaker-sale-1600978103.jpg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "product",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "8",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://www.dhresource.com/0x0/f2/albu/g2/M01/D7/53/rBVaG1Z7yPeAZyVbAALpWonCzOk728.jpg/fashion-new-qulaity-pu-leather-men-wallets.jpg",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "9",
    price: 15,
    imgUrl:
      "https://cdn.mena-tech.com/wp-content/uploads/2021/08/MR-Future-Products-2020-2.png",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "product",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "10",
    price: 15,
    imgUrl:
      "https://cdn.mena-tech.com/wp-content/uploads/2021/08/MR-Future-Products-2020-2.png",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "product",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "11",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://images.prismic.io/rushordertees-web/c46d32cd-469a-49a9-b175-7362171d29a7_Custom+Short+Sleeve+T-Shirt.jpg?auto=compress%2Cformat&rect=0%2C0%2C800%2C900&w=800&h=900",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "12",
    price: 15,
    imgUrl:
      "https://4.imimg.com/data4/AA/HC/MY-26596027/men-s-fancy-t-shirt-500x500.jpg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    off: 5,
    type: "product",
    oldPrice: 20,
  },
  {
    id: "13",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://contents.mediadecathlon.com/p1981373/k$9b63009207eb708712157b83d42dd74b/adults-category-3-hiking-sunglasses-mh140.jpg?&f=800x800",
    price: 518.68,
    rating: 4,
    type: "product",
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "14",
    price: 15,
    imgUrl:
      "https://www.eisenberg.com/upload/images/eisenberg/4f/173_BANNER-CATEGORIE-FRAGRANCE-1170X500PX.jpeg",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "15",
    name: "test item",
    imgUrl:
      "https://cdn.shopify.com/s/files/1/0505/7019/9217/products/P04.jpg?v=1613769249",
    price: 518.68,
    rating: 4,
    type: "product",
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "16",
    price: 15,
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-secret-sneaker-sale-1600978103.jpg",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "17",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://www.dhresource.com/0x0/f2/albu/g2/M01/D7/53/rBVaG1Z7yPeAZyVbAALpWonCzOk728.jpg/fashion-new-qulaity-pu-leather-men-wallets.jpg",
    price: 518.68,
    rating: 4,
    type: "product",
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "18",
    price: 15,
    imgUrl:
      "https://cdn.mena-tech.com/wp-content/uploads/2021/08/MR-Future-Products-2020-2.png",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    off: 5,
    type: "product",
    oldPrice: 20,
  },
  {
    id: "19",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://images.prismic.io/rushordertees-web/c46d32cd-469a-49a9-b175-7362171d29a7_Custom+Short+Sleeve+T-Shirt.jpg?auto=compress%2Cformat&rect=0%2C0%2C800%2C900&w=800&h=900",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
    type: "product",
  },
  {
    id: "20",
    price: 15,
    imgUrl:
      "https://4.imimg.com/data4/AA/HC/MY-26596027/men-s-fancy-t-shirt-500x500.jpg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    off: 5,
    type: "product",
    oldPrice: 20,
  },
  {
    id: "21",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://contents.mediadecathlon.com/p1981373/k$9b63009207eb708712157b83d42dd74b/adults-category-3-hiking-sunglasses-mh140.jpg?&f=800x800",
    price: 518.68,
    rating: 4,
    type: "product",
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "22",
    price: 15,
    imgUrl:
      "https://www.eisenberg.com/upload/images/eisenberg/4f/173_BANNER-CATEGORIE-FRAGRANCE-1170X500PX.jpeg",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "23",
    name: "test item",
    imgUrl:
      "https://cdn.shopify.com/s/files/1/0505/7019/9217/products/P04.jpg?v=1613769249",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "24",
    price: 15,
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-secret-sneaker-sale-1600978103.jpg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "product",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "25",
    price: 15,
    imgUrl:
      "https://cdn.mena-tech.com/wp-content/uploads/2021/08/MR-Future-Products-2020-2.png",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    off: 5,
    type: "product",
    oldPrice: 20,
  },
  {
    id: "26",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://images.prismic.io/rushordertees-web/c46d32cd-469a-49a9-b175-7362171d29a7_Custom+Short+Sleeve+T-Shirt.jpg?auto=compress%2Cformat&rect=0%2C0%2C800%2C900&w=800&h=900",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "27",
    price: 15,
    imgUrl:
      "https://4.imimg.com/data4/AA/HC/MY-26596027/men-s-fancy-t-shirt-500x500.jpg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "product",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "28",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://contents.mediadecathlon.com/p1981373/k$9b63009207eb708712157b83d42dd74b/adults-category-3-hiking-sunglasses-mh140.jpg?&f=800x800",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "29",
    price: 15,
    imgUrl:
      "https://www.eisenberg.com/upload/images/eisenberg/4f/173_BANNER-CATEGORIE-FRAGRANCE-1170X500PX.jpeg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    type: "product",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "30",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://images.prismic.io/rushordertees-web/c46d32cd-469a-49a9-b175-7362171d29a7_Custom+Short+Sleeve+T-Shirt.jpg?auto=compress%2Cformat&rect=0%2C0%2C800%2C900&w=800&h=900",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
    type: "product",
  },
  {
    id: "31",
    price: 15,
    imgUrl:
      "https://4.imimg.com/data4/AA/HC/MY-26596027/men-s-fancy-t-shirt-500x500.jpg",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "32",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://contents.mediadecathlon.com/p1981373/k$9b63009207eb708712157b83d42dd74b/adults-category-3-hiking-sunglasses-mh140.jpg?&f=800x800",
    price: 518.68,
    rating: 4,
    type: "product",
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "33",
    price: 15,
    imgUrl:
      "https://www.eisenberg.com/upload/images/eisenberg/4f/173_BANNER-CATEGORIE-FRAGRANCE-1170X500PX.jpeg",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "34",
    name: "test item",
    imgUrl:
      "https://cdn.shopify.com/s/files/1/0505/7019/9217/products/P04.jpg?v=1613769249",
    price: 518.68,
    rating: 4,
    type: "product",
    cashBack: "5%",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "35",
    price: 15,
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-secret-sneaker-sale-1600978103.jpg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    off: 5,
    type: "product",
    oldPrice: 20,
  },
  {
    id: "36",
    price: 15,
    imgUrl:
      "https://cdn.mena-tech.com/wp-content/uploads/2021/08/MR-Future-Products-2020-2.png",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "37",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://images.prismic.io/rushordertees-web/c46d32cd-469a-49a9-b175-7362171d29a7_Custom+Short+Sleeve+T-Shirt.jpg?auto=compress%2Cformat&rect=0%2C0%2C800%2C900&w=800&h=900",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "38",
    price: 15,
    imgUrl:
      "https://4.imimg.com/data4/AA/HC/MY-26596027/men-s-fancy-t-shirt-500x500.jpg",
    name: "test item",
    rating: 3,
    type: "product",
    cashBack: "5%",
    off: 5,
    oldPrice: 20,
  },
  {
    id: "39",
    name: "Camera Digital with extra lenses",
    imgUrl:
      "https://contents.mediadecathlon.com/p1981373/k$9b63009207eb708712157b83d42dd74b/adults-category-3-hiking-sunglasses-mh140.jpg?&f=800x800",
    price: 518.68,
    rating: 4,
    cashBack: "5%",
    type: "product",
    off: 10,
    oldPrice: 600,
  },
  {
    id: "40",
    price: 15,
    imgUrl:
      "https://www.eisenberg.com/upload/images/eisenberg/4f/173_BANNER-CATEGORIE-FRAGRANCE-1170X500PX.jpeg",
    name: "test item",
    rating: 3,
    cashBack: "5%",
    off: 5,
    type: "service",
    oldPrice: 20,
  },
];
