import { ServiceAdaptation, ShopStatus, ServiceType } from "@features/API";
import { SearchServiceQuery } from "@UI";

export const FAKE_FILTERED_SERVICES: SearchServiceQuery["searchServices"] = {
  __typename: "ServiceSearchResponse",
  hasMore: true,
  total: 100,
  data: [
    {
      __typename: "Service",
      id: "service-1",
      name: "Service",
      price: "250",
      beds: 2,
      bathrooms: 2,
      adaptedFor: [ServiceAdaptation.NewBorn],
      airCondition: true,
      gpsAvailable: false,
      seats: null,
      windows: 4,
      lugaggeCapacity: null,
      treatmentCategory: null,
      maxSpeedInKm: null,
      brand: null,
      description: "A service description.",
      ingredients: null,
      cleaningFee: 50,
      reviews: 85,
      thumbnail: "/shop.jpeg",
      rating: 4.8,
      type: ServiceType.Hotel,
      title: "Luxury Suite",
      speciality: "Dentist",
      availableAppointments: null,
      healthCenterBookedAppointments: [],
      saved: true,
      sellerId: "seller-1",
      updatedAt: "2024-12-08T12:00:00.000Z",
      shop: {
        __typename: "Shop",
        id: "shop-1",
        status: ShopStatus.Active,
        location: {
          __typename: "Location",
          address: "123 Main Street",
          city: "Metropolis",
          country: "Countryland",
          lat: 40.7128,
          long: -74.006,
          state: "Stateville",
        },
        sellerProfile: {
          __typename: "Profile",
          username: "LuxurySeller",
          verified: true,
          photo: "/shop-2.jpeg",
        },
      },
    },
    {
      __typename: "Service",
      id: "service-2",
      name: "Service",
      price: "40",
      beds: null,
      bathrooms: null,
      adaptedFor: null,
      airCondition: true,
      gpsAvailable: true,
      seats: 4,
      windows: 4,
      lugaggeCapacity: 2,
      treatmentCategory: null,
      maxSpeedInKm: 180,
      brand: "EconomyBrand",
      description: "A service description.",
      ingredients: null,
      cleaningFee: 10,
      reviews: 64,
      thumbnail: "/shop.jpeg",
      rating: 4.2,
      type: ServiceType.Vehicle,
      title: "Compact Car",
      speciality: "Dentist",
      availableAppointments: null,
      healthCenterBookedAppointments: [],
      saved: false,
      sellerId: "seller-2",
      updatedAt: "2024-12-08T12:00:00.000Z",
      shop: {
        __typename: "Shop",
        id: "shop-2",
        status: ShopStatus.Active,
        location: {
          __typename: "Location",
          address: "456 Side Street",
          city: "Smalltown",
          country: "Countryland",
          lat: 38.8977,
          long: -77.0365,
          state: "Stateburg",
        },
        sellerProfile: {
          __typename: "Profile",
          username: "CarRentalPro",
          verified: false,
          photo: "/shop-2.jpeg",
        },
      },
    },

    {
      __typename: "Service",
      id: "service-1",
      name: "Service",
      price: "250",
      beds: 2,
      bathrooms: 2,
      adaptedFor: [ServiceAdaptation.NewBorn],
      airCondition: true,
      gpsAvailable: false,
      seats: null,
      windows: 4,
      lugaggeCapacity: null,
      treatmentCategory: null,
      maxSpeedInKm: null,
      brand: null,
      description: "A service description.",
      ingredients: null,
      cleaningFee: 50,
      reviews: 85,
      thumbnail: "/shop.jpeg",
      rating: 4.8,
      type: ServiceType.Hotel,
      title: "Luxury Suite",
      speciality: "Dentist",
      availableAppointments: null,
      healthCenterBookedAppointments: [],
      saved: true,
      sellerId: "seller-1",
      updatedAt: "2024-12-08T12:00:00.000Z",
      shop: {
        __typename: "Shop",
        id: "shop-1",
        status: ShopStatus.Active,
        location: {
          __typename: "Location",
          address: "123 Main Street",
          city: "Metropolis",
          country: "Countryland",
          lat: 40.7128,
          long: -74.006,
          state: "Stateville",
        },
        sellerProfile: {
          __typename: "Profile",
          username: "LuxurySeller",
          verified: true,
          photo: "/shop-2.jpeg",
        },
      },
    },

    {
      __typename: "Service",
      id: "service-1",
      name: "Service",
      price: "250",
      beds: 2,
      bathrooms: 2,
      adaptedFor: [ServiceAdaptation.NewBorn],
      airCondition: true,
      gpsAvailable: true,
      seats: 4,
      windows: 4,
      lugaggeCapacity: 3,
      treatmentCategory: null,
      maxSpeedInKm: null,
      brand: null,
      description: "A service description.",
      ingredients: null,
      cleaningFee: 50,
      reviews: 85,
      thumbnail: "/shop.jpeg",
      rating: 4.8,
      type: ServiceType.Hotel,
      title: "Luxury Suite",
      speciality: "Dentist",
      availableAppointments: null,
      healthCenterBookedAppointments: [],
      saved: true,
      sellerId: "seller-1",
      updatedAt: "2024-12-08T12:00:00.000Z",
      shop: {
        __typename: "Shop",
        id: "shop-1",
        status: ShopStatus.Active,
        location: {
          __typename: "Location",
          address: "123 Main Street",
          city: "Metropolis",
          country: "Countryland",
          lat: 40.7128,
          long: -74.006,
          state: "Stateville",
        },
        sellerProfile: {
          __typename: "Profile",
          username: "LuxurySeller",
          verified: true,
          photo: "/shop-2.jpeg",
        },
      },
    },
  ],
};
