import React from "react";
import VehicleServiceCard from "./VehicleServiceCard";

const services = [
  {
    id: "1",
    image: "https://picsum.photos/400/300?random=1",
    price: "$250",
    priceType: "Hour",
    title: "Auto Care by Alex",
    provider: "Moto rent",
    location: "1208, Geneva",
    reviews: 230,
    rating: 4.7,
  },
  {
    id: "2",
    image: "https://picsum.photos/400/300?random=2",
    price: "$250",
    priceType: "Week",
    title: "Vehicle Detailing by Chris",
    provider: "Car rent",
    location: "1208, Geneva Airport",
    reviews: 1230,
    rating: 4.8,
  },
  {
    id: "3",
    image: "https://picsum.photos/400/300?random=3",
    price: "$250",
    priceType: "Day",
    title: "Tire Services by Emily",
    provider: "Car rent",
    location: "1208, Geneva Airport",
    reviews: 530,
    rating: 4.6,
  },
  {
    id: "4",
    image: "https://picsum.photos/400/300?random=4",
    price: "$250",
    priceType: "Month",
    title: "Car Wash by Ryan",
    provider: "Car rent",
    location: "1208, Geneva Airport",
    reviews: 800,
    rating: 4.9,
  },
  {
    id: "5",
    image: "https://picsum.photos/400/300?random=5",
    price: "$150",
    priceType: "Hour",
    title: "Scooter Rental by Max",
    provider: "City scooters",
    location: "1201, Geneva Downtown",
    reviews: 120,
    rating: 4.5,
  },
  {
    id: "6",
    image: "https://picsum.photos/400/300?random=6",
    price: "$500",
    priceType: "Day",
    title: "Luxury Car Rental by Sophia",
    provider: "Elite Wheels",
    location: "1202, Geneva Lake Side",
    reviews: 980,
    rating: 4.9,
  },
  {
    id: "7",
    image: "https://picsum.photos/400/300?random=7",
    price: "$300",
    priceType: "Week",
    title: "SUV Rental by David",
    provider: "Travel Cars",
    location: "1203, Geneva Central",
    reviews: 670,
    rating: 4.7,
  },
  {
    id: "8",
    image: "https://picsum.photos/400/300?random=8",
    price: "$200",
    priceType: "Day",
    title: "Minivan by Sarah",
    provider: "Family Rides",
    location: "1204, Geneva South",
    reviews: 450,
    rating: 4.6,
  },
  {
    id: "9",
    image: "https://picsum.photos/400/300?random=9",
    price: "$1200",
    priceType: "Month",
    title: "Truck Rental by James",
    provider: "Cargo Moves",
    location: "1205, Geneva West",
    reviews: 220,
    rating: 4.4,
  },
  {
    id: "10",
    image: "https://picsum.photos/400/300?random=10",
    price: "$80",
    priceType: "Hour",
    title: "Bicycle Rental by Laura",
    provider: "Eco Bikes",
    location: "1206, Geneva Park",
    reviews: 540,
    rating: 4.3,
  },
  {
    id: "11",
    image: "https://picsum.photos/400/300?random=11",
    price: "$350",
    priceType: "Week",
    title: "Convertible by Michael",
    provider: "Sunshine Rides",
    location: "1207, Geneva East",
    reviews: 310,
    rating: 4.8,
  },
  {
    id: "12",
    image: "https://picsum.photos/400/300?random=12",
    price: "$600",
    priceType: "Day",
    title: "Jeep Rental by Olivia",
    provider: "Adventure Cars",
    location: "1209, Geneva North",
    reviews: 410,
    rating: 4.7,
  },
];

export default function VehicleServiceGrid() {
  return (
    <div className="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
      {services.map((service) => (
        <VehicleServiceCard key={service.id} {...service} />
      ))}
    </div>
  );
}
