module.exports = {
  globals: {
    "ts-jest": {
      diagnostics: {
        warnOnly: false,
      },
    },
  },
  collectCoverageFrom: [
    "!**/*.{ts,tsx}",
    "**/seller/**/*.{ts,tsx}",
    "**/buyer/**/*.{ts,tsx}",
    "**/market/**/*.{ts,tsx}",
    "**/ui/**/*.{ts,tsx}",
    "!**/market/pages/stories/*.{ts,tsx}",
    "!**/*.stories.{ts,tsx}",
    "!**/node_modules/**",
    "!**/.storybook/**",
    "!**/tests/**",
    "!**/coverage/**",
    "!jest.config.js",
  ],
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  setupFiles: ["<rootDir>/config/setup.js"],
  preset: "ts-jest",
  testPathIgnorePatterns: [
    "/.next/",
    "/node_modules/",
    "/lib/",
    "/tests/",
    "/coverage/",
    "/.storybook/",
  ],
  testRegex: "(/__test__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
  testURL: "http://localhost",
  testEnvironment: "jsdom",
  moduleFileExtensions: ["ts", "tsx", "js", "json"],
  moduleNameMapper: {
    "\\.(css|less)$": "<rootDir>/__mocks__/styleMock.js",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|jfif)$":
      "<rootDir>/__mocks__/fileMock.js",
    "@UI": ["<rootDir>/packages/ui"],
    "^@UI/(.+)$": ["<rootDir>/packages/ui/$1"],
    "@partials": ["<rootDir>/packages/ui/components/partials"],
    "@blocks": ["<rootDir>/packages/ui/components/blocks"],
    "^@blocks/(.+)$": ["<rootDir>/packages/ui/components/blocks/$1"],
    "^@sections/(.+)$": ["<rootDir>/packages/ui/components/sections/$1"],
    "^@features/(.+)$": ["<rootDir>/packages/ui/components/features/$1"],
    "@sections": ["<rootDir>/packages/ui/components/sections"],
    "@features": ["<rootDir>/packages/ui/components/features"],
    "@libs": ["<rootDir>/packages/ui/libs"],
    "@const": ["<rootDir>/packages/ui/constants"],
    "^@src/(.+)$": ["<rootDir>/packages/ui/src/$1"],
  },
  transform: {
    "^.+\\.(ts|tsx)?$": "ts-jest",
    "^.+\\.(js|jsx)$": "babel-jest",
  },
  transformIgnorePatterns: ["<rootDir>/node_modules/"],
  snapshotSerializers: ["enzyme-to-json/serializer"],
};
