export const SERVICE_PRESENTATION_MAX_CONTENT_UPLOAD_LIMIT = 10;
export const SERVICE_PRESENTATION_MIN_CONTENT_UPLOAD_LIMIT = 1;
export const SERVICE_MAX_LANGUAGE_TRANSLATION_RESOURCE_LIMIT = 10;
export const SERVICE_MIN_LANGUAGE_TRANSLATION_RESOURCE_LIMIT = 10;
