module.exports = {
  moduleFileExtensions: ["js", "json", "ts"],
  rootDir: ".",
  testRegex: ".*\\.spec\\.ts$",
  transform: {
    "^.+\\.(ts|tsx)?$": "ts-jest",
    "^.+\\.(js|jsx)$": "babel-jest",
  },
  collectCoverageFrom: ["**/*.(t|j)s"],
  moduleNameMapper: {
    "@partials": ["components/partials"],
    "@blocks": ["components/blocks"],
    "^@blocks/(.+)$": ["components/blocks/*"],
    "^@sections/(.+)$": ["components/sections/*"],
    "^@features/(.+)$": ["components/features/*"],
    "@sections": ["components/sections"],
    "@features": ["components/features"],
    "@libs": ["libs"],
    "@const": ["constants"],
    "^@src/(.+)$/*": ["src/*"],
    "@UI": ["."],
    "^@UI/(.+)$": ["./$1"],
  },
  coverageDirectory: "../coverage",
  testEnvironment: "node",
  globalSetup: "<rootDir>/test/setup/globalSetup.ts",
  globalTeardown: "<rootDir>/test/setup/globalTeardown.ts",
  setupFilesAfterEnv: ["<rootDir>/test/setup/setupFile.ts"],
};
