module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(ts|tsx)?$': 'ts-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  moduleNameMapper: {
    // Force module uuid to resolve with the CJS entry point, because Jest does not support package.json.exports. See https://github.com/uuidjs/uuid/issues/451
    uuid: require.resolve('uuid'),
    '@entities': '<rootDir>/src/entities/index.ts',
    prismaClient: '<rootDir>/prisma/generated/index.js',
    '@input': '<rootDir>/src/dto/index.ts',
    '@exceptions': '<rootDir>/src/exceptions/index.ts',
    '@profile-error-messages': '<rootDir>/src/profile/profileErrorMessage.ts',
    prismaService: '<rootDir>/src/prisma.service.ts',
    '@content-management': '<rootDir>/src/content-management',
    '@profile': '<rootDir>/src/profile',
    '@content-discovery': '<rootDir>/src/content-discovery',
    '@comments': '<rootDir>/src/comments',
    '^@comments/(.+)$': '<rootDir>/src/comments/$1',
    '@keys': '<rootDir>/src/keys',
    '@posts-newsfeed': '<rootDir>/src/newsfeed-posts',
    '@prisma-module': '<rootDir>/src/app.module',
    '^@block/(.+)$': '<rootDir>/src/block/$1',
    '^@privacy-settings/(.+)$': '<rootDir>/src/privacy/$1',
    '@kafkaModule': '<rootDir>/src/kafka.module.ts',
    '^@story/(.+)$': '<rootDir>/src/story/$1',
    '^@affiliation-post/(.+)$': '<rootDir>/src/affiliation-post/$1',
    '^@product-post/(.+)$': '<rootDir>/src/product-post/$1',
    '^@action/(.+)$': '<rootDir>/src/action/$1',
    '^@hidden-content/(.+)$': '<rootDir>/src/hidden-content/$1',
    '@kafkaModule': '<rootDir>/src/kafka.module.ts',
  },
  globalSetup: '<rootDir>/test/setup/globalSetup.ts',
  globalTeardown: '<rootDir>/test/setup/globalTeardown.ts',
  setupFilesAfterEnv: ['<rootDir>/test/setup/setupFile.ts'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
};
